// Code generated by Webpb compiler, do not edit.
// https://github.com/jg513/webpb

import * as Webpb from 'webpb';

export interface IarticleEntryPb {
    id: string;
    title: string;
    category: string;
    coverImage?: string;
    publishAt?: string;
    author?: string;
}

export class articleEntryPb implements IarticleEntryPb {
    id!: string;
    title!: string;
    category!: string;
    coverImage?: string;
    publishAt?: string;
    author?: string;
    META: () => Webpb.WebpbMeta;

    private constructor(p?: IarticleEntryPb) {
        Webpb.assign(p, this, []);
        this.META = () => (p && {
            class: 'articleEntryPb',
            method: '',
            path: ''
        }) as Webpb.WebpbMeta;
    }

    static create(properties: IarticleEntryPb): articleEntryPb {
        return new articleEntryPb(properties);
    }
}
