// Code generated by Webpb compiler, do not edit.
// https://github.com/jg513/webpb

import * as Webpb from 'webpb';

export interface IarticlePb {
    id: string;
    title: string;
    category: string;
    coverImage?: string;
    publishAt?: string;
    author?: string;
}

export class articlePb implements IarticlePb {
    id!: string;
    title!: string;
    category!: string;
    coverImage?: string;
    publishAt?: string;
    author?: string;
    META: () => Webpb.WebpbMeta;

    private constructor(p?: IarticlePb) {
        Webpb.assign(p, this, []);
        this.META = () => (p && {
            class: 'articlePb',
            method: '',
            path: ''
        }) as Webpb.WebpbMeta;
    }

    static create(properties: IarticlePb): articlePb {
        return new articlePb(properties);
    }
}
