// Code generated by Webpb compiler, do not edit.
// https://github.com/jg513/webpb

import * as Webpb from 'webpb';

export enum ErrorCode {
    OK = 0,
    ERROR = 1,
}

export interface IErrorMessage {
    errCode: ErrorCode;
    message?: string;
}

export class ErrorMessage implements IErrorMessage {
    errCode!: ErrorCode;
    message?: string;
    META: () => Webpb.WebpbMeta;

    private constructor(p?: IErrorMessage) {
        Webpb.assign(p, this, []);
        this.META = () => (p && {
            class: 'ErrorMessage',
            method: '',
            path: ''
        }) as Webpb.WebpbMeta;
    }

    static create(properties: IErrorMessage): ErrorMessage {
        return new ErrorMessage(properties);
    }
}
