// Code generated by Webpb compiler, do not edit.
// https://github.com/jg513/webpb

import * as Webpb from 'webpb';

export interface IAny {
    type_url: string;
    value: Uint8Array;
}

export class Any implements IAny {
    type_url!: string;
    value!: Uint8Array;
    META: () => Webpb.WebpbMeta;

    private constructor(p?: IAny) {
        Webpb.assign(p, this, []);
        this.META = () => (p && {
            class: 'Any',
            method: '',
            path: ''
        }) as Webpb.WebpbMeta;
    }

    static create(properties: IAny): Any {
        return new Any(properties);
    }
}
