// Code generated by Webpb compiler, do not edit.
// https://github.com/jg513/webpb

import * as Webpb from 'webpb';

import * as ResourceProto from './ResourceProto';

export interface IMessagePb {
    id: string;
    title: string;
    summary: string;
    category: string;
    link?: string;
    unread?: boolean;
}

export class MessagePb implements IMessagePb {
    id!: string;
    title!: string;
    summary!: string;
    category!: string;
    link?: string;
    unread?: boolean;
    META: () => Webpb.WebpbMeta;

    private constructor(p?: IMessagePb) {
        Webpb.assign(p, this, []);
        this.META = () => (p && {
            class: 'MessagePb',
            method: '',
            path: ''
        }) as Webpb.WebpbMeta;
    }

    static create(properties: IMessagePb): MessagePb {
        return new MessagePb(properties);
    }
}

export interface IMessageDetailPb {
    id: string;
    title: string;
    content: string;
}

export class MessageDetailPb implements IMessageDetailPb {
    id!: string;
    title!: string;
    content!: string;
    META: () => Webpb.WebpbMeta;

    private constructor(p?: IMessageDetailPb) {
        Webpb.assign(p, this, []);
        this.META = () => (p && {
            class: 'MessageDetailPb',
            method: '',
            path: ''
        }) as Webpb.WebpbMeta;
    }

    static create(properties: IMessageDetailPb): MessageDetailPb {
        return new MessageDetailPb(properties);
    }
}

export interface IMessageRequest {
    pageable: ResourceProto.IPageablePb;
}

export class MessageRequest implements IMessageRequest, Webpb.WebpbMessage {
    pageable!: ResourceProto.IPageablePb;
    META: () => Webpb.WebpbMeta;

    private constructor(p?: IMessageRequest) {
        Webpb.assign(p, this, []);
        this.META = () => (p && {
            class: 'MessageRequest',
            method: 'GET',
            path: `/api/messages${Webpb.query({
                page: Webpb.getter(p, 'pageable.page'),
                size: Webpb.getter(p, 'pageable.size'),
            })}`
        }) as Webpb.WebpbMeta;
    }

    static create(properties: IMessageRequest): MessageRequest {
        return new MessageRequest(properties);
    }
}

export interface IMessageDetailRequest {
    id: string;
}

export class MessageDetailRequest implements IMessageDetailRequest, Webpb.WebpbMessage {
    id!: string;
    META: () => Webpb.WebpbMeta;

    private constructor(p?: IMessageDetailRequest) {
        Webpb.assign(p, this, []);
        this.META = () => (p && {
            class: 'MessageDetailRequest',
            method: 'GET',
            path: `/api/messages/${Webpb.query({
                id: p.id,
            })}`
        }) as Webpb.WebpbMeta;
    }

    static create(properties: IMessageDetailRequest): MessageDetailRequest {
        return new MessageDetailRequest(properties);
    }
}

export interface IMessageResponse {
    data: IMessagePb[];
    unreadCount: number;
    paging: ResourceProto.IPagingPb;
}

export class MessageResponse implements IMessageResponse {
    data!: IMessagePb[];
    unreadCount!: number;
    paging!: ResourceProto.IPagingPb;
    META: () => Webpb.WebpbMeta;

    private constructor(p?: IMessageResponse) {
        Webpb.assign(p, this, []);
        this.META = () => (p && {
            class: 'MessageResponse',
            method: '',
            path: ''
        }) as Webpb.WebpbMeta;
    }

    static create(properties: IMessageResponse): MessageResponse {
        return new MessageResponse(properties);
    }
}

export interface IMessageDetailResponse {
    data: IMessageDetailPb;
}

export class MessageDetailResponse implements IMessageDetailResponse {
    data!: IMessageDetailPb;
    META: () => Webpb.WebpbMeta;

    private constructor(p?: IMessageDetailResponse) {
        Webpb.assign(p, this, []);
        this.META = () => (p && {
            class: 'MessageDetailResponse',
            method: '',
            path: ''
        }) as Webpb.WebpbMeta;
    }

    static create(properties: IMessageDetailResponse): MessageDetailResponse {
        return new MessageDetailResponse(properties);
    }
}
